name: Build, Push and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 52.7.54.68
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "Stopping and removing existing container..."
          docker rm -f myapp || true
          
          echo "Pulling latest Docker image from Docker Hub..."
          docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:latest
          
          echo "Starting new container..."
          docker run -d --name myapp -p 80:5000 ${{ secrets.DOCKER_USERNAME }}/myapp:latest
